language: ruby

rvm:
  - 2.4.6

sudo: false
cache: bundler

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - make ci

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
