markdown: kramdown
highlighter: rouge
excerpt_separator: "<!--more-->"
permalink: /blog/:year/:month/:day/:title/
paginate_path: /blog/page:num/
paginate: 5

google_analytics_id: UA-39314903-5

repository: https://github.com/jpitz/jpitz.github.io

name: "jpitz: building better software"
url: http://jpitz.github.io
author:
  name: Jaye Pitzeruse
  email: jpitzeruse@gmail.com

exclude: [
  jpitz.github.io.iml, Gemfile, Gemfile.lock
]

include: [
  pages
]

keep_files: [
  statics
]

gems: [
  jekyll-archives,
  jekyll-feed,
  jekyll-paginate,
  jekyll-sitemap,
  jekyll-watch
]

tags:
 docker: "Docker"
 indeed: "Indeed"
 spring-bad-practices: "Spring Bad Practices"

jekyll-archives:
  enabled: [
    year,
    month,
    tags
  ]
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/:month/'
    day: '/archive/:year/:month/:day/'
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'

jekyll-sitemap:
  source: '_site'
