markdown: kramdown
highlighter: pygments
excerpt_separator: ""
permalink: /blog/:year/:month/:day/:title/
paginate_path: /blog/page:num/
paginate: 5

google_analytics_id: UA-39314903-5

repository: https://github.com/jpitz/jpitz.github.io

name: "microsrc"
url: http://jpitz.github.io
author:
  name: Jeremy Pitzeruse
  email: jpitzeruse@gmail.com

exclude: [
  jpitz.github.io.iml, Gemfile, Gemfile.lock
]

keep_files: [
  statics
]

gems: [
  jekyll-feed,
  jekyll-watch,
  jekyll-paginate
]