markdown: kramdown
highlighter: rouge
excerpt_separator: "<!--more-->"
permalink: /blog/:year/:month/:day/:title/
paginate_path: /blog/page/:num/
paginate: 5

google_analytics_id: UA-39314903-5

repository: https://github.com/mjpitz/mjpitz.com

env: production

name: "Mya Pitzeruse"
url: https://www.mjpitz.com
author:
  name: Mya Pitzeruse
  email: j.mya.pitz@gmail.com

exclude:
  - .idea
  - docker-compose.yml
  - mjpitz.com.iml
  - Gemfile
  - Gemfile.lock
  - s3_website.yml
  - deploy.sh

include:
  - pages

keep_files:
  - statics

gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-watch

tags:
 docker: "Docker"
 indeed: "Indeed"
 spring-bad-practices: "Spring Bad Practices"

jekyll-archives:
  enabled:
    - year
    - tags
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/:month/'
    day: '/archive/:year/:month/:day/'
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'

jekyll-sitemap:
  source: '_site'
