image: ruby:latest

pipelines:
  default:
    - step:
        script:
          - bundler --version
          - bundle install
          - bundle exec jekyll build
  branches:
    master:
      - step:
          script:
            - bundler --version
            - bundle install
            - bundle exec jekyll build
