baseURL = "https://mjpitz.com/"
languageCode = "en-us"
title = "Mya Pitzeruse"
theme = "anatole"
enableRobotsTXT = true

[permalinks]
blog = "/blog/:year/:month/:day/:slug/"

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Mya Pitzeruse"
author = "Mya Pitzeruse"
description = ""
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/mjpitz/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/mjpitz"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/_mjpitz_"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"
